---
author:
  - 'Robert Rothenberg <rrwo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Find::Rule: 0
  File::Temp: 0
  Image::Size: 0
  Test::Exception: 0
  Test::More: 0
  Test::Most: 0
  Test::Warnings: 0
  aliased: 0
  if: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.10'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Imager-Bing-MapLayer
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Type::Tiny::XS: 0
requires:
  Carp: 0
  Class::MOP::Method: 0
  Const::Exporter: 0
  Const::Fast: 0
  Cwd: 0
  Exporter::Lite: 0
  Imager: 0
  List::MoreUtils: 0.07
  List::Util: 1.3
  Module::Load: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  POSIX::2008: 0
  Path::Class: 0
  Type::Tiny: 0
  namespace::autoclean: 0
  perl: 5.10.1
  version: 0.77
resources:
  bugtracker: https://github.com/robrwo/Imager-Bing-MapLayer/issues
  homepage: http://rrwo.tumblr.com
  license: artistic2
  repository: git://github.com/robrwo/Imager-Bing-MapLayer.git
version: 0.001008
